name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
    branches:
      - main
jobs:
  build-and-deploy:
    environment: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Use bun ${{ matrix.bun-version }} 🍞
        uses: oven-sh/setup-bun@v2

      - name: Install 🔧
        run: bun install --frozen-lockfile

      - name: Build 🏗️
        run: bun run build
        env:
          VITE_APP_EMAILJS_SVC_ID: ${{ secrets.VITE_APP_EMAILJS_SVC_ID }}
          VITE_APP_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_APP_EMAILJS_PUBLIC_KEY }}
          VITE_APP_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_APP_EMAILJS_TEMPLATE_ID }}

      - name: Deploy to GH Pages
        run: |
          git config --global user.name 'JinHao-L'
          git config --global user.email 'JinHao-L@users.noreply.github.com'
          git remote set-url origin https://git:${DEPLOY_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          bunx gh-pages -d dist --cname ${CNAME}
        env:
          CNAME: ${{ vars.CNAME }}
          DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
